version: '3.8'

services:
  # SQL Server for E2E testing
  sqlserver-e2e:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-e2e
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./docker/sql/init:/opt/sql-scripts
      - ./docker/sql/init/init-databases.sh:/opt/init-databases.sh
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      chmod +x /opt/init-databases.sh &&
      /opt/init-databases.sh &&
      wait
      "
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd123 -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 30s
    networks:
      - e2e-network

  # Azurite for Azure Storage emulation
  azurite-e2e:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-e2e
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    command: ["azurite", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "--location", "/workspace", "--debug", "/workspace/debug.log"]
    volumes:
      - azurite-data:/workspace
    networks:
      - e2e-network

# Test runner is disabled to avoid proxy issues
# Tests will be run from the host machine directly

volumes:
  azurite-data:
    driver: local

networks:
  e2e-network:
    driver: bridge