----------------------------------------------------------------------
-- 顧客DM機器・サービス情報部分
-- 共有所有機器、TES、警報機、電力CIS契約情報、各種サービス情報
----------------------------------------------------------------------

SELECT [顧客キー_Ax] AS CLIENT_KEY_AX
      , [LIV0共有所有機器_コンロ種別] AS LIV0SPD_KONRO_SHBT
      , [LIV0共有所有機器_コンロ種別名] AS LIV0SPD_KONRO_SHBT_NAME
      , [LIV0共有所有機器_コンロ_所有機器番号] AS LIV0SPD_KONRO_POSSESSION_EQUIPMENT_NO
      , [LIV0共有所有機器_コンロ_販売先コード] AS LIV0SPD_KONRO_SL_DEST_CD
      , [LIV0共有所有機器_コンロ_製造年月] AS LIV0SPD_KONRO_DT_MANUFACTURE
      , [LIV0共有所有機器_コンロ_経年数] AS LIV0SPD_KONRO_NUM_YEAR
      , [LIV0共有所有機器_コンロ_経年数カテゴリ] AS LIV0SPD_KONRO_NUM_YEAR_CATEGORY
      , [LIV0共有所有機器_給湯機種別] AS LIV0SPD_KYTK_SHBT
      , [LIV0共有所有機器_給湯機種名称] AS LIV0SPD_KYTK_NAME
      , [LIV0共有所有機器_給湯器_所有機器番号] AS LIV0SPD_KYTK_POSSESSION_DEVICE_NO
      , [LIV0共有所有機器_給湯器_販売先コード] AS LIV0SPD_KYTK_SL_DESTINATION_CD
      , [LIV0共有所有機器_給湯器_製造年月] AS LIV0SPD_KYTK_DT_MANUFACTURE
      , [LIV0共有所有機器_給湯器_経年数] AS LIV0SPD_KYTK_NUM_YEAR
      , [LIV0共有所有機器_給湯器_経年数カテゴリ] AS LIV0SPD_KYTK_NUM_YEAR_CATEGORY
      , [LIV0共有所有機器_210_炊飯器] AS LIV0SPD_210_RICE_COOKER
      , [LIV0共有所有機器_220_レンジ] AS LIV0SPD_220_MICROWAVE
      , [LIV0共有所有機器_230_オーブン] AS LIV0SPD_230_OVEN
      , [LIV0共有所有機器_240_コンベック] AS LIV0SPD_240_CONVECTION_OVEN
      , [LIV0共有所有機器_250_コンビネーションレンジ] AS LIV0SPD_250_COMBINATION_MICROWAVE
      , [LIV0共有所有機器_300_乾燥機ほか] AS LIV0SPD_300_DRYING_MACHINE
      , [LIV0共有所有機器_310_ドライヤー（衣類乾燥機）] AS LIV0SPD_310_DRIER
      , [LIV0共有所有機器_410_金網ストーブ] AS LIV0SPD_410_WIRE_MESH_STOVE
      , [LIV0共有所有機器_420_開放型ストーブ] AS LIV0SPD_420_OPEN_STOVE
      , [LIV0共有所有機器_430_ＦＨストーブ] AS LIV0SPD_430_FH_STOVE
      , [LIV0共有所有機器_440_ＢＦストーブ] AS LIV0SPD_440_BF_STOVE
      , [LIV0共有所有機器_450_ＦＦストーブ] AS LIV0SPD_450_FF_STOVE
      , [LIV0共有所有機器_460_ＦＥストーブ] AS LIV0SPD_460_FE_STOVE
      , NULL AS TESHSMC_SERIAL_NUMBER -- TES熱源機情報_製造番号　カンマを含むためNULLに設定
      , [TES熱源機情報_システム種別] AS TESHSMC_SYSTEM_SHBT
      , [TES熱源機情報_システム落成日] AS TESHSEQ_SYSTEM_COMPLETION_DATE
      , [TES熱源機情報_メンテ区分コード] AS TESHSEQ_MAINTENANCE_TYPE_CD
      , [TES熱源機情報_所有形態コード] AS TESHSEQ_OWNER_TYPE_CD
      , [TES熱源機情報_取付年月日] AS TESHSEQ_ATTACHMENT_YMD
      , [TES熱源機情報_取外年月日] AS TESHSEQ_REMOVAL_YMD
      , [TES熱源機情報_TESメンテ加入資格有無] AS TESHSEQ_TES_MAINT_ELIGIBILITY
      , [TES放熱器情報_床暖房有無] AS TESHRDTR_UNDER_FLOOR_HEATING
      , [TES放熱器情報_バス暖房有無] AS TESHRDTR_BATH_HEATING
      , [TESサービス情報_TESメンテ加入有無] AS TESSV_MAINTENANCE_JOIN
      , [TESサービス情報_サービス番号] AS TESSV_SERVICE_ID
      , [TESサービス情報_サービス満了年月] AS TESSV_SERVICE_EXPIRATION_YM
      , [TESサービス情報_サービス種別] AS TESSV_SERVICE_SHBT
      , [警報機情報_警報器台数] AS ARMC_COUNT
      , [警報機情報_警報器取外し済みフラグ] AS ARMC_REMOVED_FLG
      , [警報機情報_警報器リース中フラグ] AS ARMC_UNDER_LEASE_FLG
      , [警報機情報_警報器リース終了フラグ] AS ARMC_LEASE_END_FLG
      , [電力CIS契約情報_お客様登録番号_3x] AS EPCISCRT_3X
      , [電力CIS契約情報_電灯_電力契約番号] AS EPCISCRT_LIGHTING_SA_ID
      , [電力CIS契約情報_電灯_使用開始日] AS EPCISCRT_LIGHTING_START_USE_DATE
      , [電力CIS契約情報_電灯_使用中止日] AS EPCISCRT_LIGHTING_END_USE_DATE
      , [電力CIS契約情報_電灯_契約ステータス] AS EPCISCRT_LIGHTING_CRT_STATUS
      , [電力CIS契約情報_電灯_使用中止理由] AS EPCISCRT_LIGHTING_RESN_DISCONTION_USE
      , [電力CIS契約情報_電灯_契約タイプ] AS EPCISCRT_LIGHTING_CRT_TYPE
      , [電力CIS契約情報_電灯_契約タイプ_名称] AS EPCISCRT_LIGHTING_CRT_TYPE_NAME
      , [電力CIS契約情報_電灯_契約タイプ_合算・単独分類] AS EPCISCRT_LIGHTING_CRT_TYPE_COMBIN_SINGLE
      , [電力CIS契約情報_電灯_支払方法] AS EPCISCRT_LIGHTING_SHRI_METHOD
      , [電力CIS契約情報_電灯_支払方法名] AS EPCISCRT_LIGHTING_SHRI_METHOD_NAME
      , [電力CIS契約情報_電灯_料金メニュー] AS EPCISCRT_LIGHTING_PRICE_MENU
      , [電力CIS契約情報_電灯_料金メニュー名] AS EPCISCRT_LIGHTING_PRICE_MENU_NAME
      , [電力CIS契約情報_電灯_契約電流] AS EPCISCRT_LIGHTING_CRT_ELECT_CURRENT
      , [電力CIS契約情報_電灯_契約容量] AS EPCISCRT_LIGHTING_CRT_CAPACITY
      , [電力CIS契約情報_電灯_契約電力] AS EPCISCRT_LIGHTING_CRT_ELECT_POWER
      , [電力CIS契約情報_電灯_契約電力kW換算値] AS EPCISCRT_LIGHTING_CRT_ELECT_POWER_KW
      , [電力CIS契約情報_電灯_用途コード] AS EPCISCRT_LIGHTING_USAGE_CD
      , [電力CIS契約情報_電灯_電気用途名] AS EPCISCRT_LIGHTING_ELECT_USAGE_NAME
      , [電力CIS契約情報_電灯_電気用途分類] AS EPCISCRT_LIGHTING_ELECT_USAGE_BRI
      , [電力CIS契約情報_電灯_電気用途家庭用詳細] AS EPCISCRT_LIGHTING_USAGE_FAMILY_DETAIL
      , [電力CIS契約情報_動力_電力契約番号] AS EPCISCRT_POWER_SA_ID
      , [電力CIS契約情報_動力_使用開始日] AS EPCISCRT_POWER_START_USE_DATE
      , [電力CIS契約情報_動力_使用中止日] AS EPCISCRT_POWER_END_USE_DATE
      , [電力CIS契約情報_動力_契約ステータス] AS EPCISCRT_POWER_CRT_STATUS
      , [電力CIS契約情報_動力_使用中止理由] AS EPCISCRT_POWER_RESN_DISCONTION_USE
      , [電力CIS契約情報_動力_契約タイプ] AS EPCISCRT_POWER_CRT_TYPE
      , [電力CIS契約情報_動力_契約タイプ_名称] AS EPCISCRT_POWER_CRT_TYPE_NAME
      , [電力CIS契約情報_動力_契約タイプ_合算・単独分類] AS EPCISCRT_POWER_CRT_TYPE_COMBIN_SINGLE
      , [電力CIS契約情報_動力_支払方法] AS EPCISCRT_POWER_SHRI_METHOD
      , [電力CIS契約情報_動力_支払方法名] AS EPCISCRT_POWER_SHRI_METHOD_NAME
      , [電力CIS契約情報_動力_料金メニュー] AS EPCISCRT_POWER_PRICE_MENU
      , [電力CIS契約情報_動力_料金メニュー名] AS EPCISCRT_POWER_PRICE_MENU_NAME
      , [電力CIS契約情報_動力_契約電流] AS EPCISCRT_POWER_CRT_ELECT_CURRENT
      , [電力CIS契約情報_動力_契約容量] AS EPCISCRT_POWER_CRT_CAPACITY
      , [電力CIS契約情報_動力_契約電力] AS EPCISCRT_POWER_CRT_ELECT_POWER
      , [電力CIS契約情報_動力_契約電力kW換算値] AS EPCISCRT_POWER_CRT_ELECT_POWER_KW
      , [電力CIS契約情報_動力_用途コード] AS EPCISCRT_POWER_USAGE_CD
      , [電力CIS契約情報_動力_電気用途名] AS EPCISCRT_POWER_ELECT_USAGE_NAME
      , [電力CIS契約情報_動力_電気用途分類] AS EPCISCRT_POWER_ELECT_USAGE_BRI
      , [電力CIS契約情報_動力_電気用途家庭用詳細] AS EPCISCRT_POWER_ELECT_USAGE_FAMILY_DETAIL
      , [電力CIS契約情報_電力契約中フラグ] AS EPCISCRT_ELECT_UNDER_CRT_FLG
      , [電力CIS契約情報_電力解約済みフラグ] AS EPCISCRT_ELECT_CANCELLED_FLG
      , [電力CIS契約情報_電灯契約数] AS EPCISCRT_LIGHTING_CONTRACT_COUNT
      , [電力CIS契約情報_動力契約数] AS EPCISCRT_POWER_CONTRACT_CRT_COUNT
      , [電力CIS契約情報_電灯合計kW] AS EPCISCRT_LIGHTING_TOTAL_KW
      , [電力CIS契約情報_動力合計kW] AS EPCISCRT_POWER_CONTRACT_TOTAL_KW
FROM [omni].[顧客DM]
