name: ADF Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          # 既存のコンテナを停止・削除
          docker ps -a | grep 'adf-test' | awk '{print $1}' | xargs -r docker rm -f
          
          # コンテナのビルドと実行
          docker build -t adf-test .
          docker run -d \
            --name adf-test \
            -p 10000:10000 \
            -p 10001:10001 \
            -p 10002:10002 \
            -p 2222:2222 \
            -p 8080:80 \
            adf-test
          
          # コンテナの状態確認
          docker ps -a
          sleep 10  # Azuriteの起動を待つ
          
          # Azuriteの状態確認
          docker logs adf-test

      - name: Run tests
        run: |
          # pytest を使用してテストを実行
          docker exec adf-test python3 -m pytest /tests/unit/ -v

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Deploy
        run: |
          # Azureへのデプロイコマンド
          echo "Deploying to Azure..."
          az deployment group create \
            --name adf-deploy \
            --resource-group adf-rg01 \
            --template-file src/factory/adf-rg01.json \
            --parameters @src/factory/publish_config.json
