name: ADF Deploy

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Remove existing adf-test container
        run: docker rm -f adf-test || true

      - name: Build test image
        run: docker build -t adf-test-image .
      
      - name: Run test container
        run: |
          docker run -d --name adf-test \
            -p 10000:10000 \
            -p 10001:10001 \
            -p 10002:10002 \
            -p 2222:2222 \
            adf-test-image tail -f /dev/null
      
      - name: Wait for container
        run: sleep 5
      
      - name: Verify Python environment
        run: |
          docker exec adf-test bash -c "
            source /opt/venv/bin/activate && \
            python --version && \
            pip list | grep pytest && \
            ls -la /tests/
          "
      
      - name: Run pytest
        run: |
          docker exec adf-test bash -c "
            source /opt/venv/bin/activate && \
            export PYTHONPATH=/tests && \
            cd /tests && \
            python -m pytest unit/ -v --tb=short --no-header
          "
      
      - name: Get logs on failure
        if: failure()
        run: |
          echo \"Container logs:\"
          docker logs adf-test
          echo \"Container processes:\"
          docker exec adf-test ps aux || true
      
      - name: Cleanup
        if: always()
        run: docker rm -f adf-test
